// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const sceneGround5 = new Entity("Scene Ground")
engine.addEntity(sceneGround5)
const sceneGround5transform = new Transform({
  position: new Vector3(0, 0, 0),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
sceneGround5.addComponentOrReplace(sceneGround5transform)
const sceneGround5GLTFShape = new GLTFShape("models/SceneGround.glb")
sceneGround5GLTFShape.withCollisions = true
sceneGround5GLTFShape.isPointerBlocker = true
sceneGround5GLTFShape.visible = true
sceneGround5.addComponentOrReplace(sceneGround5GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arrow2mWide8 = new Entity("Arrow2m Wide")
engine.addEntity(arrow2mWide8)
const arrow2mWide8transform = new Transform({
  position: new Vector3(6, 2.5, 56.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
arrow2mWide8.addComponentOrReplace(arrow2mWide8transform)
const arrow2mWide8GLTFShape = new GLTFShape("models/Arrow2mWide.glb")
arrow2mWide8GLTFShape.withCollisions = true
arrow2mWide8GLTFShape.isPointerBlocker = true
arrow2mWide8GLTFShape.visible = true
arrow2mWide8.addComponentOrReplace(arrow2mWide8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arrow2mWide29 = new Entity("Arrow2m Wide2")
engine.addEntity(arrow2mWide29)
const arrow2mWide29transform = new Transform({
  position: new Vector3(18.25, 2.5, 56.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
arrow2mWide29.addComponentOrReplace(arrow2mWide29transform)
arrow2mWide29.addComponentOrReplace(arrow2mWide8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arrow2mWide310 = new Entity("Arrow2m Wide3")
engine.addEntity(arrow2mWide310)
const arrow2mWide310transform = new Transform({
  position: new Vector3(39.25, 2.5, 53.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
arrow2mWide310.addComponentOrReplace(arrow2mWide310transform)
arrow2mWide310.addComponentOrReplace(arrow2mWide8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arrow2mWide411 = new Entity("Arrow2m Wide4")
engine.addEntity(arrow2mWide411)
const arrow2mWide411transform = new Transform({
  position: new Vector3(39.25, 2.5, 35),
  rotation: new Quaternion(0, -1.490116E-08, 0, 1),
  scale: new Vector3(1, 1, 1)
})
arrow2mWide411.addComponentOrReplace(arrow2mWide411transform)
arrow2mWide411.addComponentOrReplace(arrow2mWide8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const arrow2mWide512 = new Entity("Arrow2m Wide5")
engine.addEntity(arrow2mWide512)
const arrow2mWide512transform = new Transform({
  position: new Vector3(39, 2.5, 16),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
arrow2mWide512.addComponentOrReplace(arrow2mWide512transform)
arrow2mWide512.addComponentOrReplace(arrow2mWide8GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const firstdialoguecollision15 = new Entity("FirstDialogueCollision")
engine.addEntity(firstdialoguecollision15)
const firstdialoguecollision15transform = new Transform({
  position: new Vector3(3.25, 1.5, 53.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 3, 9)
})
firstdialoguecollision15.addComponentOrReplace(firstdialoguecollision15transform)
const firstdialoguecollision15boxShape = new BoxShape()
firstdialoguecollision15.addComponentOrReplace(firstdialoguecollision15boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const seconddialoguecollision16 = new Entity("SecondDialogueCollision")
engine.addEntity(seconddialoguecollision16)
const seconddialoguecollision16transform = new Transform({
  position: new Vector3(35, 1.5, 46),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(10, 3, 1)
})
seconddialoguecollision16.addComponentOrReplace(seconddialoguecollision16transform)
const seconddialoguecollision16boxShape = new BoxShape()
seconddialoguecollision16.addComponentOrReplace(seconddialoguecollision16boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const thirdcollision21 = new Entity("ThirdCollision")
engine.addEntity(thirdcollision21)
const thirdcollision21transform = new Transform({
  position: new Vector3(41.5, 1.5, 17.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 3, 10)
})
thirdcollision21.addComponentOrReplace(thirdcollision21transform)
const thirdcollision21boxShape = new BoxShape()
thirdcollision21.addComponentOrReplace(thirdcollision21boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  sceneGround:{
    entity: sceneGround5,
    transform: sceneGround5transform,
    GLTFShape: sceneGround5GLTFShape,
  },
  arrow2mWide:{
    entity: arrow2mWide8,
    transform: arrow2mWide8transform,
    GLTFShape: arrow2mWide8GLTFShape,
  },
  arrow2mWide2:{
    entity: arrow2mWide29,
    transform: arrow2mWide29transform,
    GLTFShape: arrow2mWide8GLTFShape,
  },
  arrow2mWide3:{
    entity: arrow2mWide310,
    transform: arrow2mWide310transform,
    GLTFShape: arrow2mWide8GLTFShape,
  },
  arrow2mWide4:{
    entity: arrow2mWide411,
    transform: arrow2mWide411transform,
    GLTFShape: arrow2mWide8GLTFShape,
  },
  arrow2mWide5:{
    entity: arrow2mWide512,
    transform: arrow2mWide512transform,
    GLTFShape: arrow2mWide8GLTFShape,
  },
  firstdialoguecollision:{
    entity: firstdialoguecollision15,
    transform: firstdialoguecollision15transform,
    boxShape: firstdialoguecollision15boxShape,
  },
  seconddialoguecollision:{
    entity: seconddialoguecollision16,
    transform: seconddialoguecollision16transform,
    boxShape: seconddialoguecollision16boxShape,
  },
  thirdcollision:{
    entity: thirdcollision21,
    transform: thirdcollision21transform,
    boxShape: thirdcollision21boxShape,
  },
}

